version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy

    environment:
    
      KEYCLOAK_USER: admin

      KEYCLOAK_PASSWORD: admin

      DB_ADDR: keycloak.c9rtbg5m3hwd.us-east-1.rds.amazonaws.com

      DB_USER: root

      DB_PASSWORD: password

      DB_VENDOR: mysql
      
      DB_DATABASE: keycloak
      
      DB_PORT: 3306
      
      JAVA_OPTS_APPEND: "-Djboss.as.management.blocking.timeout=7200"
      
      JDBC_PARAMS: "connectTimeout=30000"
